# Generated by Django 5.0.6 on 2024-06-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='profile_pic',
            field=models.ImageField(default='', upload_to='instructor/'),
        ),
    ]
