# Generated by Django 5.0.6 on 2024-06-25 15:12

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_instructor_profile_pic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Subject', 'verbose_name_plural': 'Subjects'},
        ),
        migrations.AlterField(
            model_name='instructor',
            name='profile_pic',
            field=models.ImageField(default='', upload_to=courses.models.upload_to),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_slug',
            field=models.SlugField(blank=True, max_length=90, unique=True),
        ),
    ]
